name = "MakieThemeing"
uuid = "24dc64cf-9d0d-406f-af0b-13a4c1186bb2"
authors = ["Datseris <datseris.george@gmail.com>"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
Makie = "≥ 0.19"
DrWatson = "2"
julia = "1.9"